version: 1.0.{build}
os: Visual Studio 2019
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

# restore NuGet packages before running
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m

build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal

test_script:  
  - cd tests\WebDriver.Extension.Tests
  - dotnet test